import type { Metadata } from "next";
import { Lexend_Deca } from "next/font/google";
import {AntdRegistry} from "@ant-design/nextjs-registry";
import 'material-symbols';
import "@/app/globals.css";

// Chỉ sử dụng Lexend Deca làm font chính
const lexendDeca = Lexend_Deca({
  subsets: ["latin", "vietnamese"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-lexend-deca",
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Sea food restaurant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={lexendDeca.className}>
      <body>
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
