import type { Metadata } from "next";
import { Lexend_Deca } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import 'material-symbols';
import "@/app/globals.css";
import { CartProvider } from "@/context/CartContext"; // Import context

const lexendDeca = Lexend_Deca({
  subsets: ["latin", "vietnamese"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-lexend-deca",
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Sea food restaurant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={lexendDeca.className}>
      <body>
        <AntdRegistry>
          <CartProvider> 
            {children}
          </CartProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
